<span class="st_sharethis_custom" st_url="http://sharethis.com" st_title="Sharing Rocks!">
    <img src="//www.sharethis.com/wp-content/themes/sharethis/images/header-logo.png">
</span>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">
    stLight.options({
        publisher: "17494b01-07fd-4174-a9a4-070239fa6298",
        doNotHash: false,
        doNotCopy: false,
        hashAddressBar: false,
        popup: false,
        onhover: false
    });
</script>
<style>
.st_sharethis_custom {
    width: 248px; height: 78px;
    padding:0px;
    cursor: pointer;
}
</style>