<!DOCTYPE html>
<html>
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Header -->
    	<?php echo $this->partial("layouts/header") ?>
    <!-- Title -->
        <?php echo $this->tag->getTitle() ?>
    </head>
    <body>
    <!-- NavBar -->
    	<div id="navbar">
    	<?php echo $this->partial("layouts/navbar") ?>
    	</div>

    <!-- Content -->
    	<div id="container">
        <?php echo $this->getContent() ?>
        </div>

    <!-- Footer -->
        <div id="foot">
        <?php echo  $this->partial("layouts/footer") ?>
        </div>
    </body>
</html>
