<header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
  <div class="mdl-layout--large-screen-only mdl-layout__header-row">
  </div>
  <div class="mdl-layout__header-row">
    <h3><?php echo $this->translate->_('pages.welcome', ['name' => 'Pie']); ?></h3>
  </div>
  <div class="mdl-layout--large-screen-only mdl-layout__header-row">
  </div>
  <div class="mdl-layout--large-screen-only mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
    <a href="#overview" class="mdl-layout__tab is-active">Overview</a>
    <a href="#features" class="mdl-layout__tab">Features</a>
    <a href="#features" class="mdl-layout__tab">Details</a>
    <a href="#features" class="mdl-layout__tab">Technology</a>
    <a href="#features" class="mdl-layout__tab">FAQ</a>
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent" id="add">
      <i class="material-icons">add</i>
    </button>
  </div>
</header>
<div class="mdl-layout__drawer">
  <span class="mdl-layout-title">Material Design Lite</span>
  <nav class="mdl-navigation">
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect">
      Add
    </button>
    <a href="#overview" class="mdl-navigation__link">Overview</a>
    <a href="#features" class="mdl-navigation__link">Features</a>
    <a href="#features" class="mdl-navigation__link">Details</a>
    <a href="#features" class="mdl-navigation__link">Technology</a>
    <a href="#features" class="mdl-navigation__link">FAQ</a>
  </nav>
</div>