<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Create Reservation</h1>

    <form method="post">
        <fieldset>
            <div class="control-group">
                <div class="controls">
                    <textarea style="width:100%;" class="form-control" rows="20" name="maps"></textarea>
                </div>
            </div>

            <div class="form-actions">
                <input type="submit" value="Submit" class="btn btn-primary">
                <p class="help-block">By signing up, you accept terms of use and privacy policy.</p>
            </div>
        </fieldset>

    </form>
</div>
